name: Maven Deploy

on:
  release:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Maven build
        run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: ${{ github.BUKKIT_TIMER_USER }}
          GITHUB_TOKEN: ${{ github.BUKKIT_TIMER_TOKEN }}
        run: mvn --settings settings.xml --file pom.xml deploy

